name: laundrypoint
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  shared_preferences: ^2.5.4
  intl: ^0.19.0
  image_picker: ^1.2.1
  url_launcher: ^6.3.2
  geocoding: ^3.0.0
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  webview_flutter: ^4.4.0
  firebase_core: ^4.15.0
  firebase_messaging: ^16.7.0
  firebase_database: ^12.6.0
  cloud_firestore: ^6.10.0
  flutter_local_notifications: ^22.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true