// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl_sfQ4nWR9-0_JAaDUux0Ss9jauHLs6A',
    appId: '1:647920014033:web:81e6c0262bf3445a69ebf0',
    messagingSenderId: '647920014033',
    projectId: 'pintpoint-laundry',
    authDomain: 'pintpoint-laundry.firebaseapp.com',
    databaseURL: 'https://pintpoint-laundry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pintpoint-laundry.firebasestorage.app',
    measurementId: 'G-PXJGKPL2K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYRGLdLl1UdMyuleF2jj0pcruRYKwsfe0',
    appId: '1:647920014033:android:a520d9eeb21bc4f769ebf0',
    messagingSenderId: '647920014033',
    projectId: 'pintpoint-laundry',
    databaseURL: 'https://pintpoint-laundry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pintpoint-laundry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7SnqC7EqtWTy8C7RVXWD_vfSazQl5hYo',
    appId: '1:647920014033:ios:2ced87e74ae7986d69ebf0',
    messagingSenderId: '647920014033',
    projectId: 'pintpoint-laundry',
    databaseURL: 'https://pintpoint-laundry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pintpoint-laundry.firebasestorage.app',
    iosBundleId: 'com.example.laundrypoint',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7SnqC7EqtWTy8C7RVXWD_vfSazQl5hYo',
    appId: '1:647920014033:ios:2ced87e74ae7986d69ebf0',
    messagingSenderId: '647920014033',
    projectId: 'pintpoint-laundry',
    databaseURL: 'https://pintpoint-laundry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pintpoint-laundry.firebasestorage.app',
    iosBundleId: 'com.example.laundrypoint',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl_sfQ4nWR9-0_JAaDUux0Ss9jauHLs6A',
    appId: '1:647920014033:web:8103745ccc9fda3d69ebf0',
    messagingSenderId: '647920014033',
    projectId: 'pintpoint-laundry',
    authDomain: 'pintpoint-laundry.firebaseapp.com',
    databaseURL: 'https://pintpoint-laundry-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pintpoint-laundry.firebasestorage.app',
    measurementId: 'G-J91W9W4KK3',
  );
}
